#!/bin/bash

MESSAGE_COMMIT=$1;

git add .;
git commit -m "$MESSAGE_COMMIT";
git config --global credential.helper 'cache --timeout=10800';
git push 
echo "................"
echo "................"
echo "Commit realizado com sucesso: $(tput setaf 2)$MESSAGE_COMMIT$(tput sgr0) :)";
echo "................"
echo "................"