version: '3.8'
services:
  dbblog:
    image: postgres
    container_name: db-blog
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - /mnt/postgres/orar-e-labutar:/var/lib/postgresql/data