#! /bin/bash

if [ -f "$PWD/dist/css/main.min.css" ];
    then 
        rm -rf "$PWD/dist/css/main.min.css";
        rm -rf "$PWD/dist/css/main.min.pre.css";
        echo "Preparando para iniciar minificação...";
        sleep 2;
    else
        echo "Pronto para iniciar.";
        sleep 2;
fi

SCAN_DIR_CSS=`(ls $PWD/dist/css/*.css)`;

concat_and_minify_css(){
    echo "" > minify-css.log;
    for file in $1; 
       do
        tr -s '[:space:]' ' ' < "$file" >> "$PWD/dist/css/main.min.css";
        echo "$file" >> minify-css.log;
    done
};

minify_main_css_complet(){
    count=0;
    while [ $count -le 700 ] 
    do
        sed -i 's/{ /{/' "$PWD/dist/css/main.min.css";
        sed -i 's/ }/}/' "$PWD/dist/css/main.min.css";
        sed -i 's/: /:/' "$PWD/dist/css/main.min.css";
        sed -i 's/; /;/' "$PWD/dist/css/main.min.css";

        count=$(( $count + 1 ));
    done
};

concat_and_minify_css "$SCAN_DIR_CSS";
minify_main_css_complet;

echo "------------------------------------------------";
echo "";
echo "$(tput setaf 2)Os seguintes arquivos css foram minificados e copiados para 
o arquivo main.min.css:$(tput sgr0)";
echo "";
cat minify-css.log;
echo "";
echo "------------------------------------------------";