#! /bin/bash

FILE_RESULT_MIN_CSS=$PWD/dist/css/main.min.css;

# Verifica se já existe o mesmo arquivo css minificado. Se sim, apaga.
if [ -f $FILE_RESULT_MIN_CSS ];
    then 
    rm -rf $FILE_RESULT_MIN_CSS;
fi

# Lista todos os arquivos CSSs na pasta css/
SCAN_DIR_CSS=`(ls $PWD/dist/css/*.css)`;

# Suprime todos os espaços redundantes dos arquivos .css e redireciona a saída
# para main.min.css.
concat_and_minify_css(){
    for file in $1; 
       do
        # Remove comentários inline | Suprime espaços >> redireciona a saída.
        sed '/^\/.*[\/$]/d' "$file" | tr -s '[:space:]' ' ' >> "$FILE_RESULT_MIN_CSS";
    done
};

# Termina o trabalho de minificação, removendo espaços específicos.
minify_main_css_complet(){
    sed -i -e \
        's/ {/{/g' -e \
        's/{ /{/g' -e \
        's/ } /}/g' -e \
        's/: /:/g' -e \
        's/; /;/g' -e \
        's/, /,/g' -e \
        's/ > />/g' -e \
        's/ \/ /\//g' $FILE_RESULT_MIN_CSS;
};

# Chamada das funções.
concat_and_minify_css "$SCAN_DIR_CSS";
minify_main_css_complet;

echo "$(tput setaf 2)CSS minificado:$(tput sgr0)";
echo "$(tput setaf 3)$FILE_RESULT_MIN_CSS$(tput sgr0)";