name: Integration Continuo - Nuxt Site
on: 
  push:
    branches: ['master']
  # Allows external webhook trigger
  repository_dispatch:
jobs: 
  generate-assets:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Using Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 19.x
      - name: Run Install and Generate
        run: |
          yarn install
          yarn generate
