name: Integration Continuo - Nuxt Site
on: 
  push:
    branches: ['main']
  workflow_dispatch:
  repository_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "19.x"
      - name: Generate Pages
        run: |
          yarn install
          yarn generate
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: orarelabutar
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
